### ISSUE TITLE
WP7 [B23] - Autre - Vector Time Series

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#47] opened 2017-09-12 08:48 UTC
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Develop WINS to support Time series (library, etc…)

**Comment by afabiani** [comment] 2017-10-17 08:07
I need more details on the expected results/workflow.

**Comment by meyerch** [comment] 2017-11-03 11:21
The idea is for layers with temporal data (for example a layer on water abstraction with a value on water abstraction for every year between 1990 and 2003. Layer will most probably have data per years, but it can also be per month, week, etc.), to have a space were users can visualize the variation according to the time. 

Something like this [http://tipstrategies.com/geography-of-jobs/ ] with a tme slider and the information varying accordingly: 
![timeserie1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc9d97269186bb86ecee01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b32a8a4a85bfbb8a44c0ec3522e3889d02.PNG)

**Comment by meyerch** [comment] 2017-11-03 13:59
we would also like time serie to show graph of the evolution of the serie. 
Such as what is shown here:

**Comment by meyerch** [comment] 2017-11-03 14:01
So this triggers several questions:
- does the TimeSerie will be in  a new tab?
 - how to make the link between the 'Layer' menu and the TimeSerie menu?
- we have in mind to be able to save appropriate layers as TimeSerie but also as 'regular' layers on WINS (i.e. uploading the layer showing the information for 1 year only)

Let us know if you have any questions.

**Comment by simboss** [comment] 2017-11-13 10:02
The first part is in line with our proposal but the second one is outside our initial proposal.
I will come back with a proposal to tackle this.

**Comment by simboss** [comment] 2017-11-25 15:33
Our proposal is highlited in [this](https://docs.google.com/document/d/1yoOKGfEmCCPnwIsVpRfpy9NTcB7qIOXRZiw4vGuU7uk/edit?usp=sharing) document.

**Comment by meyerch** [comment] 2018-01-18 09:34
Hi, 
So I did the test with the files you provided through the dropbox. With the shapefile as is, it works fine. 
However, I have several questions: 
- how do I upload the .csv? Should I go through the "upload layers" page ? 

- as for the layers, how to add a style to the layer? Based on the files you provided (specifically "boxes_with_date" and "boxes_with_year_field"), I added in QGIS a new column with a value for each polygons. Then I created a style with categories. But when I tried to upload them on the dev instance, I ended up with an error message "Could not find the ".dbf" file, which is mandatory", although the .dbf is present. See screenshot below (I am also sending you those 2 modified layers through email)
![dbf_missing.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ec969c1c8f8aba9ce0b144e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb28814e80b7ba884ac7ee382ce1898d5d73.PNG)

- in the file you provided, there is only one characteristic associated with each of the objects: this results in the location of the object changing according to the date. However, most of our files are different in the sense that the object is static, but the values are attributed to it change over time. For exemple: the proportion of population using safe  drinking water services, per country, between 2000 and 2015. 
In that case, we have 1 value per country for each year between 2000 and 2015. I tried to uploaded this specific file (will send it to you as well) but it is not recognized by the system as offernig a Time dimension...
Is it linked to the name of the columns, which should be formatted differently? 

THank you, and let me know if you have any questions.

**Comment by afabiani** [comment] 2018-01-19 10:58
@meyerch so after performing some checks and tests with the files and examples you provided I discovered as follows:

1. You can upload ".CSV" files exactly the same as you do with the Shapefiles; so "Layer Upload" is ok. The same for KML and KMZ overlays

2. This is a bug that I'm going to spot on a separate issue; basically the backend does not recognize CAPS letters on the file name. Renaming the files into something like "boxes_with_year_field_changedcm" it seems to work as expected. Nevertheless I will fix this ASAP. Few more things to add here:

    * Currently if you put a ".sld" file along with the others, the form prevents you to upload the Layer. This can be improved. Otherwise the SLD can be always uploaded on a second stage from the Layer Details
![image](https://user-images.githubusercontent.com/1278021/35147667-abeb8768-fd0f-11e7-830e-a530d4753614.png)

    * It should be possible in any case to "ZIP" the files along with the "SLD" also - which must have the name equal to the layer - but currently I noticed that something prevents to upload "ZIP" files - I need to investigate more on this -
![image](https://user-images.githubusercontent.com/1278021/35147749-feda305a-fd0f-11e7-8e34-39598d2f6685.png)
Probably some configuration missing since this is working fine on a clean GeoNode setup. I will open a dedicated issue to this topic also.

3. For such kind of Shapefiles currently you will need to re-format them and slightly change their internal structure. Accordingly to the OGC WMS-T (Web Map Service with Time) specs, you need a column dedicated to the temporal dimension values. A possible solution would be to refactor the file as follows:

```
OBJECTID | ISO | NAME       | UNESCOMEMB | YEAR | VALUE  |
=========|=====|============|============|======|========|
170      | MOZ | Mozambique | Mozambique | 2000 | 41.11  |
---------|-----|------------|------------|------|--------|
170      | MOZ | Mozambique | Mozambique | 2001 | 41.85  |
---------|-----|------------|------------|------|--------|
170      | MOZ | Mozambique | Mozambique | 2002 | 42.60  |
---------|-----|------------|------------|------|--------|
170      | MOZ | Mozambique | Mozambique | 2003 | 43.34  |
---------|-----|------------|------------|------|--------|
...
```

**Comment by meyerch** [comment] 2018-01-29 16:05
Hi, 
I uploaded successfully a .kml file on dev WINS. However, I am still struggling with the .csv file. 
When trying to upload a file (with no caps in the title nor in the columns' name), I end up with an error message: "Unexpected exception Unable to recognize the uploaded file(s)"
![csv_fail_upload.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46eb878c1c8482a083d6aa53a852f1906b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c1ef3f21e68d864f391f060ac4.PNG)

Am I missing something in the upload process? I am emailing you the .csv file I used when testing this out.

As for your latest point on re-formatting our files: I am currently working on an updated file to test this out. Will let you know the results. Thank you

**Comment by meyerch** [comment] 2018-03-20 11:16
Hi, 
Regarding the TimeSerie tool: 
- when confiuring the layer for TimeSerie, there is a display problem with the info box that pops up when the mouse is on 'Next'. As you can see from the exemple below, the box is out of the screen. Can you fix this to ensure the info-box always remain in the perimeter of the screen?
![timeSerie1_infobox.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc9d9726b186bb86ecee7cad53f69b2b493f316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b4bcae93827e68e8b4b3a190c1c8df84f78.PNG)

- in the French version, lots of portions of text remain in English. Is there a tool I can use to change this directly? (rather than to ask you to do it). I am interesting in knowing so, as other words/sentences over the website are not/incorrectly translated in French. 

Thanks

**Comment by meyerch** [comment] 2018-03-27 16:02
Another issue I noted: when creating a map with TimeSerie layer(s), what is shown is the latest time period available.  I take the following map as exemple for my explanations: http://ihp-wins-dev.geo-solutions.it/maps/1101 , which displays a TimeSerie layer of polygons (African countries) and another TimeSerie layer of points (cities).

The time period to be displayed can normally be chosen through the 'Layer properties' tool/'Display'/'Limit with filters'. There, the user can select to filter by year. 
Whenever I select a year to match (e.g. 'YEAR=2008'), the layer ends up disappearing as shown below. 
![map-timeSerie.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e5958a6e968aa48adaba51ad58b2d86b56357c2301a03f32dfa17de6437f555a5b18fa105d5d41aaf98928a6b23c718f5a09ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b9884ec1ee3b27e58888493b0c48.PNG)

However, when I select any condition for filter other than 'year', it works correctly. The issue is the same with the other TimeSerie layer of points on this map.
My question is: Why is the layer disappearing when selecting a 'Year' filter? Can you fix this issue?

Secondly, there is no slider to select the year/time period of interest when creating maps, whereas there is a time slider on individual layer's page, above the viewer. 
My question is: Is it possible to add a time-slider like what can be found on each layer's page (viewer), so that users can select the year they wish to display through the same tool as when on a layer's page?

**Comment by giohappy** [comment] 2018-04-11 12:55
Dear Chloe,
regarding the issue with filters by YEAR, are you still facing it? The map example you were pointing to doesn't exist anymore.

**Comment by meyerch** [comment] 2018-04-17 08:29
Dear @giohappy , 
Apologies for the lack of response. 
The map does exist, but it was not resleased publicly yet. Sorry about that. 
I have now published it, so you should be able to access it.

**Comment by afabiani** [comment] 2018-04-19 15:32
@meyerch I just did few tests with the map. I guess that the issue here is that you did not specified the correct values on the filter. I'm not sure if I correctly reproduced the use case, but if I put just the year on the filter I get pink tiles because the vectorial layer actually stores the whole date and not just the year value.

If I put the whole date format on the filter, it is correctly applied.

![2018-04-19 17_32_10-Map - ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb7bcfd3fdc2b8e603f50acfc77b7976236429a23b30c8a321b752361606010db1150d195aabacd636e5e96035ce0554b392730630d42103ecfadd45ea52fe32815d80bfedde48c5ec6b73b68e8d4a681e051b89fb5d34a59f49da44e409b01301fb4e6f29b33424765595177f2d6e6522aaf9de5f818468a3b30262.png)

**Comment by meyerch** [comment] 2018-04-20 09:12
Hi @afabiani , 

Thanks for the response. It is interesting because the layer I uploaded had only "2015" (for example) as 'year' and not "2015-01-01T00:00:00". 
I uploaded again the same layer and saved it in a map (http://ihp-wins-dev.geo-solutions.it/maps/new?copy=1112) and you can see that the field "year" has only years as values (like "2015") this time, and not "year-month-dayTtime" (ex: "2015-01-01T00:00:00"). 

Do you know why this change in value format for the 'year' column took place?

**Comment by meyerch** [comment] 2018-05-16 13:48
ok, thanks. 

I still have this issue: 
1/ when confiuring the layer for TimeSerie, there is a display problem with the info box that pops up when the mouse is on 'Next'. As you can see from the exemple below, the box is out of the screen. Can you fix this to ensure the info-box always remain in the perimeter of the screen?
![timeSerie1_infobox.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fc9d9726b186bb86ecee7cad53f69b2b493f316546b3397f8fe62bab0021435a561ff8455d5b12aaa88c29a3e03c70895c0fedd0685976d42103eee9dc4be05ce36ade0d97bcae8b45cae93827e18f88473b1f0d1189fe4f78.PNG)

and question :
2/ in the French version of the TimeSerie configuring tool, lots of portions of text remain in English. Is there a tool I can use to change this directly? (rather than to ask you to do it). I am interesting in knowing so, as other words/sentences over the website are not or incorrectly translated in French.

**Comment by afabiani** [comment] 2018-05-16 13:55
@meyerch 

1/ yes, should be just a CSS styling issue. I will look into that. Most probably won't be too difficult to fix.

2/ yes, but the procedure requires some passages to be done. Probably, if you think it might be useful for you in the future, would be better if a write down a small guide on how to manage this. In very few words, there are some ".mo" and ".po" files for each LOCALE we would like to implement. The ".po" one is  basically a text file containing the original sentences along with their translation. This must be compiled into the ".mo" one and uploaded into the LOCALE folder of the server. There's a very good tool around which helps a lot editing such files

https://poedit.net/

**Comment by afabiani** [comment] 2018-05-17 08:08
@meyerch I reduced and moved the tooltip box. Can you check if it is working correctly now?

**Comment by meyerch** [comment] 2018-05-17 08:34
@afabiani  
ok, it is within the screen now. 
Now that I can read the text in it, I don't really see the purpose of this tooltip box. Can you delete it?
 Sorry about that, thanks

**Comment by afabiani** [comment] 2018-05-17 08:36
@meyerch sure, I'll remove it, no problems.

**Comment by meyerch** [comment] 2018-05-17 09:02
Cool.

I will look at the Poedit  software to see how it works and start working on the translation. 
If you have time to set up a short guide on how to do it, this will be perfect, so I can try to handle this without bothering you.

**Comment by meyerch** [comment] 2018-05-17 09:31
@afabiani 
yes, it is perfect. THanks a lot

**Closed** 2018-05-18 08:01 UTC
Labels: Priority: High, in test, unesco-ihp, user story

**Comment by afabiani** [comment] 2018-05-18 10:34
@meyerch please find the instruction document for updating translations here

https://docs.google.com/document/d/1DKSznzz6m8PWDGNgFwdxN1jOd0s4tH8y036K96CBfYs/edit?usp=sharing

**Comment by meyerch** [comment] 2018-05-18 14:33
@afabiani  Thank you so much
