### ISSUE TITLE
Legend repeated twice in preview

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/unesco-ihp#353] opened 2021-05-13 16:19 UTC
On the preview of [this layer](http://ihp-wins.unesco.org/layers/:geonode:a__4205_Humedad), the legend is repeated twice

![dooble legend](https://user-images.githubusercontent.com/56537133/118154611-8e533f80-b417-11eb-97ba-4634343ff33a.gif)

**Comment by giohappy** [comment] 2021-05-14 09:25
@marthamareal taking into account the following:

 - this geonode project overrides tones of templates
 - it uses a specific GeoNode branch which is https://github.com/geosolutions-it/geonode/tree/ihp-wins-geonode-3.2.x

Please check if something is wrong inside the DB for this layer (duplicated styles, legends links, whatever).
If you think the problem is in the code itself give me an estimate for the cherry-picking of your recent work on GN 3.2.x that fixed several things for the legends.

**Comment by giohappy** [comment] 2021-05-14 14:29
@marthamareal please verify if it's an isolated case (repreated legened in the DB) and if the many actions that can change styles / default style work as expected:

1) create a new style through the Style Editor inside the MapStore client
2) change the default style from the Style Editor
3) set the default style from the Manage Style (see issue #354)
4) change the default style from the detail page (sidebasr)

**Comment by marthamareal** [comment] 2021-05-17 12:46
@giohappy @afabiani   Basing on the digging I have done on the issue, 
I think we will need to update the UNESCO branch with these fixes
1 . Checking of the title In the template and also using on setting the style_title as done in this [PR](https://github.com/GeoNode/geonode/pull/7256/files).
2. Fix style title as done [here](https://github.com/GeoNode/geonode/pull/7405/files)

**Comment by giohappy** [comment] 2021-05-17 13:53
please proceed @marthamareal

**Comment by marthamareal** [comment] 2021-05-18 13:12
Below is the command we will need to update the existing styles with no sld_title

**Comment by giohappy** [comment] 2021-05-18 13:46
PR https://github.com/geosolutions-it/geonode/pull/787 is merged.
@marthamareal the fix to the templates must be ported to the overridden templates in this repo. E.g. [layer_detail.html](https://github.com/geosolutions-it/unesco-ihp/blob/master/ihp/templates/layers/layer_detail.html)

**Closed** 2021-05-18 16:18 UTC
Labels: C117-UNESCO-2019-GEONODE, GeoNode, bug

**Comment by giohappy** [comment] 2021-05-19 08:56
The following command was required to remove the duplicate legend links, which made the legend still appear twice.

`python manage.py set_all_layers_metadata -d`
