### ISSUE TITLE
WP7 [B22] - Users - Login with Linkedin or facebook account

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#46] opened 2017-09-12 08:48 UTC
Ref: https://docs.google.com/spreadsheets/d/13ICjs8oJ0Vkw-Y1cSpZxJ93MQJCtASuBCsI20ECvCOM/edit#gid=623020856
 
Link WINS to LinkedIn and Facebook so that users can directly upload their profile on WINS from LinkedIn and Facebook.

**Comment by afabiani** [comment] 2017-10-17 08:06
I need more details on the expected results/workflow.

**Comment by meyerch** [comment] 2017-11-04 12:38
We want to offer the possibility to user to log in through their LinkedIn and perhaps (To be confirmed) Facebook account. The idea is that the user's profile will fill up automatically with information incoming from the LinkedIn/Facebook profile 
This will allow us to retrieve informartion from those  LinkedIn/Facebook profiles, through which we will be able to identify and reach (email to advertise for WINS. ) new potentials WINS users 

![linkedin.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49d94288787a081abf301b44fff9e2c4533317346f6727181b77deb447d005a5d4bfa41585c44f8f9882ea0b42e6c981e5ab38532022d8c6853beb2901eb70bbb258b4682bfb48f4cc8ea382cf5c6.jpg)

![linkedin2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46e49d94288787a081bbfd0fe64de29b234324676b5ee17e2984e77cea167d070e5a4ca917585f47fcfd892aa3b03e62964e49bc8f3900299f7744eeaa880dbe06b0218e4f8cb1b58249c1ee3b22ee99c2.jpg)

**Comment by simboss** [comment] 2017-11-09 11:05
It would be great if this feature is not enabled by default but rather when an administrator will explicitly enable it. 

Moreover, I guess it would be good to account for a validation step which means that users would need to be accepted before they can actually upload data and make modifications to the platform.

We should strive to contribute this back to GeoNode.

**Comment by ricardogsilva** [comment] 2017-11-16 11:13
I've been working on this feature and these are my initial considerations:

### Initial investigation

- Authorization in geonode is currently provided by the external (but still part of geonode's organization) [geonode-user-accounts](https://github.com/GeoNode/geonode-user-accounts) project. It is a fork from [pinax/django-user-accounts](https://github.com/pinax/django-user-accounts) that [adds the following features](https://github.com/pinax/django-user-accounts/compare/master...GeoNode:master):
    - account invites
    - registration approval;

    However, geonode-user-accounts deals only with local auth;
- In order to be able to login to geonode using either [linkedin](https://developer.linkedin.com/docs/oauth2) or [facebook](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) (or most of the other major sites like google, twitter, github, etc) we need to implement support in geonode for being an [Oauth2 client](https://en.wikipedia.org/wiki/OAuth#OAuth_2.0);
- There are some public Oauth2 implementations for python. [oauthlib](https://oauthlib.readthedocs.io/en/latest/index.html) seems to be the *de facto* standard package that serves as a base for concrete implementations. geonode is already using oauthlib and [django-auth-toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/) in order to serve as an Oauth provider for geoserver. Unfortunately, django-oauth-toolkit does not seem to offer functionality to also act as an Oauth client;
- [requests-oauthlib](https://requests-oauthlib.readthedocs.io/en/latest/) is recommended by oauthlib as the tool for building Oauth2 clients;
- In the [django world](https://djangopackages.org/grids/g/oauth/), there are some packages that build on requests-oauthlib in order to offer a more complete solution. The most promising of these seems to be [django-allauth](https://www.intenct.nl/projects/django-allauth/). It adds support for 50+ providers (including linkedin, facebook and most well known sites). It also features a rich set of functionality, with flows for taking care of both local and remote authorization. From their docs:
    - Signup of both local and social accounts
    - Connecting more than one social account to a local account
    - Disconnecting a social account -- requires setting a password if only the local account remains
    - Optional instant-signup for social accounts -- no questions asked
    - E-mail address management (multiple e-mail addresses, setting a primary)
    - Password forgotten flow
    - E-mail address verification flow
- With django-allauth it is also possible to [perform custom actions upon user registration](http://django-allauth.readthedocs.io/en/latest/advanced.html#creating-and-populating-user-instances). This can be used for:
    - Automatically filling in the user's profile on geonode;
    - Requiring staff approval before allowing the user to actually login, a feature currently present in geonode-user-accounts;
- Furthermore, since both geonode-user-accounts and django-allauth provide some similar functionality they are not installable side-by-side without performing some heavy customization;
- While it is desirable to keep existing auth-related functionality while also add remote login possibilities, django-allauth seems to offer a broader set of functionality than geonode-user-accounts. It also seems to be extensible;
- we can possibly retire geonode-user-accounts in favor of django-allauth, provided that there is no removal of existing functionality. This means complementing django-allauth with something extra;
- The two features that seem to be missing from django-allauth are:

    - Staff approval of new accounts - As stated above, django-allauth seems to provide appropriate extensibility that allows implementing this feature. This might go directly into geonode core repository, since it seems like a small scoped functionality;
    - User invites  - django-allauth [explicitly does not implement user invites](http://django-allauth.readthedocs.io/en/latest/advanced.html#invitations), leaving this for more specialized apps. Searching through [django-packages](https://djangopackages.org/grids/g/invitations/), it seems that the [django-invitations](https://github.com/bee-keeper/django-invitations) app might be a good choice to turn to for this feature;

During this investigation phase I've started already to do some initial code implementation, in order to get a feel of the work. I've been working on integrating django-allauth with geonode. I'm still playing around with the initial login integration. So far I seem to be able to connect an existing user account with my linkedin profile and login to geonode successfully.

### Moving forward proposal

- Go with django-allauth and retire geonode-user-accounts
- Port user registration approval code from geonode-user-accounts into main geonode, such that it is usable by django-allauth
- Use django-invitations to hanlde user invites

#### Benefits:

- Retiring geonode-user-accounts eases maintenance burden of the geonode project (less code to oversee)
- Both django-allauth and django-invitations seem to be healthy projects, with active development and good test coverage
- Geonode becomes a bit more focused on its core business

#### Downsides:

- This will require large changes to geonode. However, adding Oauth2 would probably always require some significant modifications;

@afabiani @simboss @meyerch What is your opinion?

**Comment by simboss** [comment] 2017-11-16 17:49
Quick talk with @ricardogsilva 

This approach is interesting but goes a little beyond original estimates as it would require  6to 7 days to implement.


I have asked @ricardogsilva to think about a different approach that would allow us to stay within original estimates or at least close to them.

**Comment by ricardogsilva** [comment] 2017-11-17 11:40
Thinking about different approaches to the current task, I see the following:

#### 1) Move on with django-allauth, retire geonode-user-accounts and reimplement  missing functionality

This is the original proposal, as described in my previous comment above. As I had been already working on this, current state of implementation on my local branch is:

- django-allauth is mostly integrated with geonode (still need to add some templates);
- geonode-user-accounts is not being used anymore (still need to clean up geonode's settings file and remove unused templates);
- can register new users with a local account;
- can register new users with a linkedin account (using another provider, like facebook or google is likely just a few config steps away, as this is provided by django-allauth. linkedin is being used as a test);
- can change the password of a local user;
- can set/change a password for a user who originally registered by connecting with linkedin;
- can manage (add/remove) social accounts of a user - this means a user can choose to connect with its linkedin account even if already registered on geonode. It means also that a user can connect more than one social account to its geonode user (currently only testing with linkedin). User can also disconnect a previously connected social account;
- can manage (add/remove/verify) multiple e-mail addresses for a user - there is a primary e-mail address and there may be secondary addresses too;

Still todo:

- [easy] Deal with 'forgotten password' auth flow - this is supported by django-allauth so it should be a matter of adding the correct templates;
- [easy] Make the social accounts integration optional by tweaking the login template and adding a geonode setting to control this;
- [easy] Add back geonode-user-accounts functionality of inviting users to join geonode - this means installing and wiring up the [django-invitations](https://github.com/bee-keeper/django-invitations) app
- [easy] Write some documentation on how to configure social accounts (mostly add geonode specific docs and redirect to django-allauth's docs for provider related stuff)
- [medium] Retrieve linkedin information upon user registration and use it for filling up user's geonode profile. django-allauth seems to provide useful signals for this. Alternatively the socialaccount adapter can be extended;
- [medium] Add back geonode-user-accounts functionality of moderating (approve/deny) a new user's registration - this will involve extending django-allauth

Pending work seems to be easy/medium to do, without any blockers foreseen. **It seems to me that with three days more of work this could be finished**. 

#### 2) Use a different package to provide Oauth integration

There are some additional packages for handling Oauth and social authentication with django (analysis presented down below). However, none of them seems better than django-allauth for the current task. None of them supports the features that geonode-user-account has either. So this proposal would quickly transform back into the first one once with the additional drawbacks:

- Would need to restart work of integrating new Oauth package with geonode;
- IMHO there is no better package for the task at hand currently available, so the new package would be less suitable


#### 3) Temporarily remove features that were being supplied by geonode-user-accounts

As stated previously, django-allauth does not currently have a ready-made solution for:

- inviting users to register with geonode;
- moderating a new user's registration.

A possible time-saver would be to drop these features for the time being, if they are not critical to the current project.

In terms of implementation effort, according to the description in 1) I'd only need to wrap up the remaining integration of dajngo-allauth and cleaning up after retiring geonode-user-accounts. This means **I'd probably be able to finish things up with one more day (maybe a day and a half) of work**.

This approach will make it difficult to contribute back the changes to main geonode, since there is on one hand a gain in functionality (unification of local and social auth) but on the other there are some features that cease to exist.

We might perhaps then split up another task for re-adding this functionality back to geonode?

#### 4) Have different feature sets for local and remote auth

This would mean that a user who would register for a local account would have different restrictions in its registration process than one who would register with a social account. This seems to be worse for the geonode project, as it will lead to fragmentation of the codebase by splitting similar responsabilities among different parts of the application. 

In addition to that, it will likely require some patching of geonode-user-accounts in order to work, as different auth packages might be incompatible with each other (that is the case with geonode-user-accounts and django-allauth, it might be similar with others). This is also kind of risky, as it may open up the door for undefined behaviour (and bugs) by having differently managed auth mechanisms.

## Conclusion

All in all, it seems like proposals 1) and 3) are feasible, while the others are not. Personally I'd go with 1), as it seems like there are no blockers and the estimate points to a not too long implementation cycle.

What do you think?


---

##### packages that provide Oauth2 client functionality:
This research refers to the packages present on the [django packages](https://djangopackages.org/grids/g/oauth/) website, which is usually accepted as the reference place to publish and look for django packages:

- django-allauth (the one currently being proposed)
  - active project with commercial support backing it
  - largest number of upvotes on djangopackages
  - support for large number of providers baked in
  - aims to provide complete auth solution (local auth + social auth)
  - provides default templates that are good guidance
  - has extensibility hooks for implementing missing functionality, which
    in geonode's case seems to be user invitations and staff approval of new
    accounts

- python social auth
  - active project supporting different web frameworks, in addition to django
  - similar scope as django-allauth, being a complete auth solution (local 
    auth + social auth)
  - the docs seem to indicate that it is more complex and requires a bigger 
    effort to setup
  - also does not handle user invites nor registration approval

- django-all-access

  - only provides remote auth, local auth still needs to be handled. This 
    means keeping geonode-user-accounts and also reimplementing user invites 
    and registration approval for socialauths anyway
  - relies on customization of CBVs
  - does not provide any default templates
  - seems to require a bit more effort to set up

- django-auth-adfs
  - used for authenticating against Microsoft ADFS through Oauth2
  - not useful for the task at hand

- django-oneall
  - works with the oneall platform, thus adding an extra middleman in the 
    process.
  - seems like adding another platform to the mix is adding complexity and 
    not really necessary

- django social auth
  - deprecated in favor of python social auth

- django-oauth-access 
  - seems deprecated (last commit to master in 2014, not on pypi, no test 
    coverage)

- django oauth2 consumer
  - not maintained, last commit in 2013

**Comment by simboss** [comment] 2017-11-19 16:11
After internal discussion we decided to go for the initial option as it seems much cleaner.

The estimate has been adjusted to 5 days, compreheding the investigation.

This work should be released to the community version of GeoNode.

**Comment by ricardogsilva** [comment] 2017-11-20 18:38
List of on-going functionality implementation

- [x] User can register with local account
- [x] User can register with linkedin
- [x] User can register with facebook
- [x] User profile is automatically filled with information from linkedin account
- [ ] User profile is automatically filled with information from facebook account
- [x] User can login/logout with local account
- [x] User can login/logout with linkedin
- [x] User can login/logout with facebook
- [x] User can set/change password
- [x] User can ask for password reset
- [x] User can connect/disconnect linkedin and facebook accounts after having registered
- [ ] Admin can enable or disable user registration
- [ ] Admin can enable or disable users login with social accounts
- [x] Admin can require approval of new user registration (both local and social account based registration)
- [x] Admin receives notification when a new user registration is pending moderation
- [x] User receives notification after admin has approved registration based on local account
- [ ] User receives notification after admin has approved registration based on remote account
- [ ] Admin can invite users to join the geonode site
- [ ] Unprevileged user can invite users to join geonode site
- [ ] Admin can configure whether unprivileged users may invite other users

**Comment by meyerch** [comment] 2017-11-23 11:39
Thank you for the update. We will let you know if we have any question.

**Comment by meyerch** [comment] 2017-12-18 17:39
Dear Ricardo,
Thank you for your work on this. 

Here are some comments and questions. 

1/ When a user is registering through LinkedIn, his/her profile is automatically filled with the info available on LinkedIn.  I noticed that some fields do not fill up, despite the information being available on LinkedIn. Can you ensure that the following fields do fill up on WINS from LinkedIn? :
- city, which corresponds "location within this area" on LinkedIn
- postal code, which corresponds "ZIP code" on LinkedIn
- country, which corresponds "country" on LinkedIn (however, this one is a drop-down menu, so not sure you can automatically fill it in on WINS)

**Comment by ricardogsilva** [comment] 2018-01-17 09:50
Dear @meyerch 
I'll respond to each point in a separate comment as some things take longer to write :)

1.  Automatically populate more user fields when connecting to LinkedIn

    I'll investigate a bit and add the requested fields, if they are available through LinkedIn's developer API

**Comment by ricardogsilva** [comment] 2018-01-17 12:17
**2 -  registration/login clarifications**

The registration/login process follows the [oauth2](https://oauth.net/2/) specification. A very simplified description of how oauth2 works in our case:

- Some of the major internet websites can serve as authentication providers (LinkedIn, facebook, google, etc);

- These authentication providers have a *developers area* (see for example, for [LinkedIn](https://developer.linkedin.com/)) where it is possible to create an app and request to use their services for authentication. The provider then assigns a password and some other secret data;

- In order to use this authentication scheme in geonode, the following steps have to be taken:

  - a geonode admin (or another authorized party) visits the provider's *developers area* and creates an app, taking note of the secret parameters generated by the provider;

  - back on geonode's side, the admin configures a determined provider by entering the secret parameters provided. If you check the admin section on WINS you'll find there under the *social accounts* -> *social applications* area you will find there the configuration for LinkedIn and facebook

  - After the admin has configured authentication, the rest of the process is automatic

- When a new user requests to join WINS by logging in with her LinkedIn account,  the platform does three things:

  1. It contacts LinkedIn and asks it to confirm that the user exists and is valid. This means that it is the provider that is responsible for dealing with the actual authentication. The act of verifying if the user account exists and sorting out if there are other accounts connected on the same computer and etc. is all done externally to the WINS platform, by the authentication provider.

  1. After receiving confirmation from LinkedIn, the WINS platform assumes that the user is indeed valid and proceeds to create a user account on WINS. The account is configured so that later on the user may login again via LinkedIn.

  1. After verifying the user, WINS will also request from LinkedIn some details about the user and these are added to the user's WINS profile

Does this make things a bit more clear? I can try to provide more detail if needed.

**Comment by ricardogsilva** [comment] 2018-01-17 12:32
**3 - authentication settings**

The options that were mentioned are all specified in the configurations file(s), which are found at `ihp/settings.py` and `ihp/local_settings.py`. These options are:

- `ACCOUNT_OPEN_SIGNUP` - Allows the admin to enable/disable user registration. If this is set to `False` users are not able to register unless they have been previously invited to join the platform;
- `SOCIALACCOUNT_PROVIDERS` - Specifies which external providers (if any) are available for users to login with. In our case, there are entries for LinkedIn and facebook;
- `ACCOUNT_APPROVAL_REQUIRED` - Specifies whether new user registrations are automatically accepted or if they must be manually approved by an admin first.

There are some more options related to user accounts and authentication in there too. I've provided some documentation on them which should be included in the geonode main documentation as soon as this functionality is merged into the main geonode project. [This merge is currently pending](https://github.com/GeoNode/geonode/pull/3461), as the geonode team is still reviewing the changes.

In any case, if you need more detail I can provide a description of all the authentication and user account related settings.

**Comment by ricardogsilva** [comment] 2018-01-17 12:54
**4 - access user's contacts on remote provider**

This is a trickier matter.
Both LinkedIn and facebook have implemented privacy related restrictions that disallow retrieving a user's contacts/friends.

I've done some superficial investigation and it seems that:

- LinkedIn's public services do not allow accessing a user's contacts list. However, they do have a partnership program where organizations can apply and request access to restricted services. It seems likely that accessing a user's contacts may be offered by these restricted services (I've not investigated this). More information here:

  https://developer.linkedin.com/blog/posts/2015/developer-program-changes
  https://developer.linkedin.com/partner-programs

- facebook also disallows remote access to a user's fiends list by default. There are some ways to access some of the user's friends, but they seem to be for different purposes (such as tagging a friend in a photo or post) and require a previous explicit consent by these other users. More information here:

  https://developers.facebook.com/docs/apps/faq

**Comment by ricardogsilva** [comment] 2018-01-17 16:18
@meyerch 
I've submitted code for extracting the **country** and **city** of a user from its LinkedIn profile. 

I have not implemented **postal code** extraction, as I did not have a reliable way to test it. According to [LinkedIn's documentation](https://developer.linkedin.com/docs/fields/company-profile) the postal code is not supported for all countries.

**Closed** 2018-01-19 10:08 UTC
Labels: Priority: Medium, in test, task, unesco-ihp

**Comment by meyerch** [comment] 2018-01-21 15:19
Hi, 
Thanks you for all those details. I will look at the documentation you provided and let you know if I have any other questions. 

As for your latest comment on point 1/ (retrieving city and country from LinkedIn profile) I have tested it and it works perfectly, thanks. 

Before archiving this task, I will talk to Youssef about Point 4/  accessing user's contacts on remote provider, to see what he wants and let you know.

**Comment by meyerch** [comment] 2018-01-24 09:11
After discussion with Youssef, this task is accepted and archived.
